### ISSUE TITLE
Docker builds are failing

### ISSUE THREAD

**Issue by cstuder** [cstuder/apprise-ga#7]
Error message: `The command '/bin/sh -c pip install apprise j2cli' returned a non-zero code: 1`

Seems to no longer using wheels and building some crypto-dependencies from source. :-(

**Comment by caronc** [comment]
@cstuder I'm a bit disappointed in this as well.  As it turns out  *cryptography* decided to start switching to Rust which [is going to cause apprise to lose support for a lot of architectures](https://github.com/pyca/cryptography/issues/5771).

For now you can export an environment variable just before your `pip install` command and it will build as you're used to.  But supposedly the next version of `cryptography` won't have this.
```Dockerfile
# alternatively just export this before your `pip install` call
ENV CRYPTOGRAPHY_DONT_BUILD_RUST=1
```

I'm debating making `cryptography` an optional install instead of a required one. If it's not present, i could just have the notifications that depend on it report an error to install this.  At this time it would impact just 2 services **FCM** and one other.

**Comment by cstuder** [comment]
I've released a new version using the non-Alpine Python base image and that one seems to work. Might be an Alpine issue. 

But yeah, breaking a lot of flows. :-(

**Comment by cstuder** [comment]
Fixed in latest release.
